### BASIC INTRODUCTION TO NUMPY

Numpy is a python Library for scientific and numeric computation. It provides a high performance multidimensional array object and tools for working with these arrays.

In [1]:
#Import Numpy before use
import numpy as np

#### 1-D ARRAYS

These are also called vectors (row or column vectors)

In [4]:
a = [1,2,3,4]

In [5]:
type(a)

list

In [6]:
#create 1 D array in numpy
array_1d = np.array(a)
array_1d

array([1, 2, 3, 4])

#### 2-D ARRAYS

This is also called a matrix

In [8]:
#create 2 D array in numpy
array_2d = np.array([(1,2,3,4), (2,4,6,7)])
array_2d

array([[1, 2, 3, 4],
       [2, 4, 6, 7]])

#### 3-D ARRAYS

In [9]:
#create 1 D array in numpy
array_3d = np.array([[(20,30,40), (34,45,50), (60,90,43)]])
array_3d

array([[[20, 30, 40],
        [34, 45, 50],
        [60, 90, 43]]])

### Initial Placeholders/ Default Arrays

In [14]:
#### Create an array of Zeros
arr_zeros = np.zeros((3,4,5))
arr_zeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
#### Create an array of ones
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
list(range(0,20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [19]:
#### Create an array of evenly spaced values
arr_even = np.arange(0,10, 2)
arr_even

array([0, 2, 4, 6, 8])

In [21]:
#### Create an array of evenly spaced values
arr_line = np.linspace(0,2,5)
arr_line

array([0. , 0.5, 1. , 1.5, 2. ])

In [22]:
#### Create a constant array
arr_full = np.full((2,2), 3)
arr_full

array([[3, 3],
       [3, 3]])

In [23]:
#### Create a constant array
arr_diag = np.eye(4)
arr_diag

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
#### Create an array with random values
arr_rand = np.random.random((4,4))
arr_rand

array([[0.68322739, 0.98838831, 0.00147782, 0.43655718],
       [0.537356  , 0.60203643, 0.27670907, 0.23336656],
       [0.51358947, 0.82781521, 0.48594253, 0.49020339],
       [0.37303187, 0.23733898, 0.27436703, 0.52859762]])

In [27]:
#### Create an empty array
arr_empty = np.empty((3,4))
arr_empty

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Inspecting your Arrays

In [1]:
test_array = np.array([(2,4,5), (5,6,7), (3,4,5)])
test_array

NameError: name 'np' is not defined

In [31]:
# Check the shape
test_array.shape

(3, 3)

In [32]:
#check the length
len(test_array)

3

In [67]:
a = np.array([(2,4,5), (3,4,7)])
a

In [68]:
a.ndim

2

In [64]:
#Check the dimension of an array
test_array.ndim

NameError: name 'test_array' is not defined

In [61]:
array_2d.ndim

2

In [34]:
#Check size
test_array.size

9

In [39]:
test_array = np.array([(2,4,5), (5,6,7), (3,4,5)], dtype=np.float)
test_array

array([[2., 4., 5.],
       [5., 6., 7.],
       [3., 4., 5.]])

In [40]:
#Check data types
test_array.dtype

dtype('float64')

In [41]:
#convert an array to a different type
test_array.astype(str)

array([['2.0', '4.0', '5.0'],
       ['5.0', '6.0', '7.0'],
       ['3.0', '4.0', '5.0']], dtype='<U32')

In [44]:
##3 Asking for Help
np.info(np.ndarray.conjugate)

a.conjugate()

Return the complex conjugate, element-wise.

Refer to `numpy.conjugate` for full documentation.

See Also
--------
numpy.conjugate : equivalent function


### ARRAY MATHEMATICS

In [3]:
arr1 = np.array([1,4,5])
arr2 = np.array([2,3,4])

In [4]:
## ADDITION
arr1 + arr2

array([3, 7, 9])

In [5]:
## SUBTRACTION
arr1 - arr2

array([-1,  1,  1])

In [8]:
np.add(arr1,arr2)

array([3, 7, 9])

In [9]:
## DIVISION
arr1 / arr2

array([0.5       , 1.33333333, 1.25      ])

In [82]:
## MULTIPLICATION
arr1 * arr2

array([ 2, 12, 20])

There are other trig and mathematical functions to try out. Check the documantation at [DOC](https://numpy.org)

### COMPARISON

In [11]:
arr1

array([1, 4, 5])

In [12]:
arr2

array([2, 3, 4])

In [10]:
#Element-Wise Comparison
arr1 == arr2

array([False, False, False])

In [13]:
arr1 < arr2

array([ True, False, False])

### AGGREGATE FUNCTIONS

In [14]:
temp_arr = np.array([[2,3,4], [3,4,6]])
temp_arr

array([[2, 3, 4],
       [3, 4, 6]])

In [15]:
temp_arr.sum()

22

In [16]:
temp_arr.min()

2

In [21]:
temp_arr.max(axis=0)

array([3, 4, 6])

In [22]:
temp_arr.cumsum(axis=1)

array([[ 2,  5,  9],
       [ 3,  7, 13]], dtype=int32)

In [98]:
temp_arr.std()

1.247219128924647

In [23]:
temp_arr.mean()

3.6666666666666665

### COPYING ARRAYS

In [24]:
#Shallow copy | Changes to y_array will affect original array
y_array = temp_arr

In [30]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

In [29]:
y_array[0] = [3,3,3]
y_array

array([[3, 3, 3],
       [3, 4, 6]])

In [31]:
#Deep copy | Changes to new_arr will not affect original array
new_arr = np.copy(temp_arr)
new_arr

array([[3, 3, 3],
       [3, 4, 6]])

### SLICING, SUBSETTING AND INDEXING

Works like normal list functions

In [32]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

In [36]:
#Subsetting
temp_arr[1]

array([3, 4, 6])

In [63]:
#Slicing

#temp[row : column]

temp_arr[0,1:3]

array([3, 3])

In [48]:
#Boolean Indexing

temp_arr[temp_arr == 3]

array([3, 3, 3, 3])

### ARRAY MANIPULATION

In [49]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

In [50]:
#Tranposing
atrans = temp_arr.T
atrans

array([[3, 3],
       [3, 4],
       [3, 6]])

In [51]:
#Change Shape
temp_arr.ravel()  #Flatten Array

array([3, 3, 3, 3, 4, 6])

In [52]:
temp_arr

array([[3, 3, 3],
       [3, 4, 6]])

In [57]:
#Reshape
temp_arr.reshape(3,5)

ValueError: cannot reshape array of size 6 into shape (3,5)

In [58]:
#Combining arrays
a = np.array([2,3,4])
b = np.array([4,5,6])

np.concatenate((a,b))

array([2, 3, 4, 4, 5, 6])

In [147]:
#Stack Array Row wise
np.vstack((a,b))

array([[2, 3, 4],
       [4, 5, 6]])

In [148]:
#Stack Array column wise
np.hstack((a,b))

array([2, 3, 4, 4, 5, 6])

In [60]:
a

array([2, 3, 4])

In [151]:
#Stack columns
np.column_stack((a,b))

array([[2, 4],
       [3, 5],
       [4, 6]])

In [ ]:
arr